# Edit this file to reflect your database settings

development:
    adapter: postgresql
    user: user
    database: dtc_dev
    
production:
    adapter: sqlite3
    database: db/production.sqlite.db
    
test:
    adapter: sqlite3
    database: db/test.sqlite.db